name: self_park
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  http: ^1.1.0
  postgres: ^2.6.1
  postgresql2: ^1.0.4
  dio: ^5.2.1+1
  socket_io_client: ^2.0.2
  stomp_dart_client: ^0.4.4
  web_socket_channel: ^2.4.0
  uuid: ^3.0.7
  shelf_proxy: ^1.0.4
  shelf: ^1.4.1
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  dropdown_button2: ^2.3.6
  flutter_map: ^5.0.0
  latlong2: ^0.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
